# Generated by Django 6.0.2 on 2026-03-16 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perceived_benefits', models.IntegerField(blank=True, null=True)),
                ('self_efficacy', models.IntegerField(blank=True, null=True)),
                ('barrier_time', models.IntegerField(blank=True, null=True)),
                ('barrier_tired', models.IntegerField(blank=True, null=True)),
                ('barrier_others', models.IntegerField(blank=True, null=True)),
                ('performed_activity', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('walking', models.CharField(blank=True, max_length=50, null=True)),
                ('running', models.CharField(blank=True, max_length=50, null=True)),
                ('cycling', models.CharField(blank=True, max_length=50, null=True)),
                ('gym', models.CharField(blank=True, max_length=50, null=True)),
                ('sport', models.CharField(blank=True, max_length=50, null=True)),
                ('others', models.CharField(blank=True, max_length=50, null=True)),
                ('mood', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
