name: Deploy Mood App

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/mood-app:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/mood-app:latest

    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Deploy to VM using docker
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF

        cd ~

        if [ ! -d "psychic-mood" ]; then

          git clone https://github.com/VITAE-01/psychic-mood.git

          mkdir -p ~/psychic-mood/psychic_data
        fi

        cd psychic-mood

        cat <<EOT > .env
        ${{ secrets.ENV_FILE }}
        EOT

        sudo docker pull ghcr.io/${{ github.repository_owner }}/mood-app:latest

        sudo docker-compose stop web
        sudo docker-compose rm -f web
        sudo docker-compose up -d web

        EOF