name: Deploy App

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Deploy to VM using docker
      run: |

        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF

        cd ~

        if [ ! -d "psychic-mood" ]; then

          git clone https://github.com/VITAE-01/psychic-mood.git

          mkdir -p ~/psychic-mood/psychic_data
        fi

        cd psychic-mood

        cat <<EOT > .env
        ${{ secrets.ENV_FILE }}
        EOT

        git pull origin main

        docker-compose up -d --build web

        EOF