name: Deploy Mood App

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Prepare GHCR namespace
      id: prep
      run: echo "namespace=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ steps.prep.outputs.namespace }}/${{ github.event.repository.name }}:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ steps.prep.outputs.namespace }}/${{ github.event.repository.name }}:latest

    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Deploy to VM using docker
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF

        cd ~

        if [ ! -d "psychic-mood" ]; then

          git clone https://github.com/VITAE-01/psychic-mood.git

          mkdir -p ~/psychic-mood/psychic_data
        fi

        cd psychic-mood

        git pull origin main

        cat <<EOT > .env
        ${{ secrets.ENV_FILE }}
        EOT

        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

        docker pull ghcr.io/${{ steps.prep.outputs.namespace }}/${{ github.event.repository.name }}:latest

        docker-compose stop web
        docker-compose rm -f web
        docker-compose up -d web

        EOF